# Generated by Django 2.1.1 on 2018-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keybase_proofs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keybaseproof',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
